apiVersion: apps/v1
kind: Deployment
metadata:
  name: ipark-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ipark-backend
  template:
    metadata:
      labels:
        app: ipark-backend
    spec:
      containers:
        - name: ipark-backend
          image: ipark-app:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "384Mi"
              cpu: "300m"
          env:
            - name: JAVA_TOOL_OPTIONS
              value: "-Xms128m -Xmx256m"