apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: ipark-secrets-provider
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "ipark/dev/secrets"
        objectType: "secretsmanager"
        jmesPath:
          - path: STRIPE_API_KEY
            objectAlias: STRIPE_API_KEY
          - path: STRIPE_API_PUBLIC_KEY
            objectAlias: STRIPE_API_PUBLIC_KEY
          - path: STRIPE_WEBHOOK_SECRET
            objectAlias: STRIPE_WEBHOOK_SECRET
  secretObjects:
    - secretName: ipark-secrets
      type: Opaque
      data:
        - objectName: STRIPE_API_KEY
          key: STRIPE_API_KEY
        - objectName: STRIPE_API_PUBLIC_KEY
          key: STRIPE_API_PUBLIC_KEY
        - objectName: STRIPE_WEBHOOK_SECRET
          key: STRIPE_WEBHOOK_SECRET