apiVersion: v1
kind: Service
metadata:
  name: ipark-service
  labels:
    app: ipark-app
spec:
  type: ClusterIP
  selector:
    app: ipark-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080